[project]
name = "morn-agent"
version = "0.0.1"
readme = "README.md"

requires-python = ">=3.11"

dependencies = [
    "fastapi",
    "uvicorn",
]

[project.urls]
Homepage = "https://github.com/morn-ai/morn-agent"
Repository = "https://github.com/morn-ai/morn-agent"
Documentation = "https://github.com/morn-ai/morn-agent#readme"

[tool.mypy]
python_version = "3.11"

[tool.ruff]
line-length = 120
