networks:
  morn:
    driver: bridge

services:
  server:
    image: hugegraph/hugegraph:latest
    container_name: server
    ports:
      - 8080:8080
    networks:
      - morn

  hubble:
    image: hugegraph/hubble:1.5.0
    container_name: hubble
    ports:
      - 8088:8088
    networks:
      - morn
